# Development environment values for tma-data-generator.

replicaCount: 1

image:
  repository: ghcr.io/ivanov-slk/tma-data-generator
  pullPolicy: IfNotPresent
  tag: "v1"

nameOverride: ""
fullnameOverride: ""

podEnvironmentVariables:
  natsServerUri: "nats://nats.tma:4222"

podAnnotations:
  config.linkerd.io/skip-inbound-ports: "4222"
  config.linkerd.io/skip-outbound-ports: "4222"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
